### PR TITLE
feat: Remove hard dependency on @scaleleap/amazon-marketplaces

### PR DESCRIPTION
**Pull request by nguyentoanit**

### CODE REVIEW

**Comment by nguyentoanit** [comment]
@moltar : I didn't got this error when `npm t` and `npm run build` on local. 
I used Windows 10 to test and build. Do this happen on your local environment?

Ref: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/207c5aa228bb7a7c8bc6ecfc0844b93e926eb7cc/test/refresh-token.ts#L41

**Comment by moltar** [comment]
> I didn't got this error

Which error?

**Comment by nguyentoanit** [comment]
> Which error?

@moltar : [This Error](https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/400/files#diff-26c0b97b9d069a3d7905beef019bbb11)

**Comment by moltar** [comment]
@nguyentoanit I've fixed the errors, feel free to merge, if you think this is ready.

**Comment by moltar** [comment]
Btw, I don't think we have completely gotten rid of the dependency here.

We are still using enums from the package. Maybe we shall refactor that to union of strings also.

I think we should only use the dependency as a devDep and not force users to install it.

**Comment by nguyentoanit** [comment]
> @nguyentoanit I've fixed the errors, feel free to merge, if you think this is ready.

Thank you. I'm going to resolve last issue before start working on another project. 😄

**Pull request merged**
