### PR TITLE
fix: converting circular structure to json

### LINKED ISSUE #643: Converting circular structure to JSON
When calling the `SponsoredProductsReportOperation.getReport()` method, the client can run into an exception where it tries to JSON.stringify() the full response object, resulting in `Converting circular structure to JSON`

See: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/src/http-client.ts#L87

Node: v14.14.0
Package Version: 1.30.9

```
"message": "Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'TLSSocket'\n    --- property '_httpMessage' closes the circle",
"stack": [
  {
    "filename": null,
    "function": null,
    "line": null
  },
  {
    "filename": null,
    "function": "stringify",
    "line": null
  },
  {
    "filename": "@scaleleap/amazon-advertising-api-sdk/lib/http-client.js",
    "function": "handleApiResponse",
    "line": 62
  },
  {
    "filename": "@scaleleap/amazon-advertising-api-sdk/lib/http-client.js",
    "function": "apiRequest",
    "line": 85
  }
```

The response of the api is the following

```
...
      host: [ 'Host', 'advertising-api-eu.amazon.com' ]
    }
  },
  data: 'Number of requests exceeded maximum allowed request rate.'
}
```

### PR DESCRIPTION
**Pull request by nguyentoanit**
Closes #643

### CODE REVIEW

**Review by moltar — COMMENTED** [review]
That is interesting!

But why would `429` fall through to `InvalidProgramStateError`?

I thought we had a special error class for `429` errors?

If not, we definitely should!

**Review by moltar — COMMENTED** [review]
Wouldn't `429` be caught here?

https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/679/files#diff-b3d62e5c74806d2b785aa734d35d46400ad94a64d80846b0a16dd2ee8fea3436R84-R86

**Comment by nguyentoanit** [comment]
@moltar 
> Wouldn't `429` be caught here?
> 
> https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/679/files#diff-b3d62e5c74806d2b785aa734d35d46400ad94a64d80846b0a16dd2ee8fea3436R84-R86

Yeah. It would be caught there if there is `code` in body response. 

> But why would 429 fall through to InvalidProgramStateError?
>I thought we had a special error class for 429 errors?

In this case, `InvalidProgramStateError` will be through if request has http status is 429 and there isn't `code`.
We had a special error class for 429 errors too and processed in [apiErrorFactory](https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/src/errors.ts#L93)

Should we only focus on http status for error checking?

**Comment by moltar** [comment]
Ok, so does that mean then that the API returns `429` without a body?

**Comment by nguyentoanit** [comment]
> Ok, so does that mean then that the API returns `429` without a body?

Not sure. I couldn't reproduce them in live API.
[From the docs](https://advertising.amazon.com/API/docs/en-us/get-started/developer-notes#Error-response:~:text=This%20is%20the%20universal%20format%20for%20error%20response%20objects.), they still mention about `code` in body. 
[But as my understand from our source code](https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/679/files#diff-b3d62e5c74806d2b785aa734d35d46400ad94a64d80846b0a16dd2ee8fea3436R84), it will only throw if there isn't `code` attribute in body?

**Comment by moltar** [comment]
>  it will only throw if there isn't code attribute in body?

That's right. And the 429 error should have code.

**Comment by nguyentoanit** [comment]
> That's right. And the 429 error should have code.

So we still check both `http status` and `code` in body?

**Comment by moltar** [comment]
I think the issue might be that the API is returning a string, instead of the object. So I added a bunch of defenses against that.

**Comment by nguyentoanit** [comment]
@moltar: Should we rebase and merge this PR to fix "Converting circular structure" error before we receive response from ownagedj in #643 ? 
We still keep issue open.

**Comment by moltar** [comment]
Yeah, let's merge.

**Comment by moltar** [comment]
I think I lost some coverage with my refactors. Please see the detailed report, it says which lines. Could you please fix that? Thanks.

**Comment by nguyentoanit** [comment]
> I think I lost some coverage with my refactors. Please see the detailed report, it says which lines. Could you please fix that? Thanks.

I got it and will resolve in next PR. Thanks.

**Pull request merged**
